source 'https://github.com/CocoaPods/Specs'
source 'https://bitbucket.org/inthepocket/itp-cocoapods-specs'

platform :ios, '<%= deployment_target %>'

# App Dependencies

pod 'ITPConfiguration'
pod 'CocoaLumberjack', '= 2.0.0-beta4'
pod 'AFNetworking'
<% if enable_parse %>pod 'Parse', '~> 1.5'<% end %>
<% if enable_googleanalytics %>pod 'GoogleAnalytics-iOS-SDK'<% end %>
# Unit Tests Dependencies

target :unit_tests, :exclusive => true do
  link_with '<%= test_target_name %>'
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
  pod 'OHHTTPStubs'
end

<% if enable_settings && use_cocoapods %>
# Copy acknowledgements to the Settings.bundle

post_install do | installer |
  require 'fileutils'

  pods_acknowledgements_path = 'Pods/Target Support Files/Pods/Pods-Acknowledgements.plist'
  settings_bundle_path = Dir.glob("**/*Settings.bundle*").first

  if File.file?(pods_acknowledgements_path)
    puts 'Copying acknowledgements to Settings.bundle'
    FileUtils.cp_r(pods_acknowledgements_path, "#{settings_bundle_path}/Acknowledgements.plist", :remove_destination => true)
  end
end
<% end %>
